[Common]
DEBUG: True

[Secret]
SECRET_KEY: c8np3^pd59j7cihwe@as58qlvxv)pr92)38b7nalv41vi1k

[Database]
ENGINE: django.db.backends.postgresql
NAME: admin
USER: admin
PASSWORD: admin
HOST: 127.0.0.1
PORT: 5432

